### ISSUE TITLE
wish: adding school holidays

### ISSUE THREAD

**Issue by feth** [profound-labs/wallcalendar#1]
I'm amazed by wallcalendar... thank you!
I'll be using it to plot our family's birthdays and school holidays.
At first, I think I am going to edit the finished PDF to add coloured lines under the corresponding weeks (we have 3 different school holidays calendar in France... perhaps it's a specific need).

**Comment by gambhiro** [comment]
Have a look at the `cal-marks` example to get started:

- [doc/examples/cal-marks.pdf](https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/cal-marks.pdf)
- [doc/examples/cal-marks.tex](https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/cal-marks.tex)
- [doc/examples/data/holidays.csv](https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/data/holidays.csv)

Keep in mind you will have to compile with `lualatex`.

As for coloured mark for intervals, I recommend adding them as annotations with a PDF editor such as the [PDF X-Change Editor](https://www.tracker-software.com/product/pdf-xchange-editor) (free).

It is way too much work to generate those with LaTeX and Lua scripts, and you will get a calendar much sooner.

**Comment by gambhiro** [comment]
By the way I also uploaded a template to Overleaf. Perhaps it helps to experiment, but eventually you almost certainly want to compile on a local machine.

https://www.overleaf.com/latex/templates/wall-calendar/yyvqfsbsmssm

**Comment by feth** [comment]
Your trick for annotating days gives great results, thank you!
And thank you too for advising pdf-xchange-editor. I'll give inkscape a
shot just to be sure :)
