### ISSUE TITLE
alignment problem with first page

### ISSUE THREAD

**Issue by anarcat** [profound-labs/wallcalendar#14]
Hi!

I am almost done with that crazy project. I am not fighting with printers and print shops and papers and grammage and all sorts of undecipherable horrors. :)

An astute print shop noticed that the cut marks on the first page were too tight, however. See this, for example:

![image](https://user-images.githubusercontent.com/796623/49609854-c57db680-f96a-11e8-8676-630722641acc.png)

This was produced with [calendes.txt](https://github.com/profound-labs/wallcalendar/files/2654709/calendes.txt) which is *I believe* fairly faithful to the original in terms of metrics.

I tried to follow the judicious advice you gave me in https://github.com/profound-labs/wallcalendar/issues/4#issuecomment-433684222 but couldn't quite figure out what was wrong. I have tried to tweak the left margin to fix the problem, but it's still not exactly centered perfectly:

![image](https://user-images.githubusercontent.com/796623/49609976-2c02d480-f96b-11e8-9072-774468f77e66.png)

I used the following naive patch:

```diff
@@ -212,7 +214,7 @@
 \mbox{}

 \AddToShipoutPictureFG*{%
-  \put(\LenToUnit{-3mm},\LenToUnit{-3mm}){%
+  \put(\LenToUnit{-4mm},\LenToUnit{-3mm}){%
     \begin{tikzpicture}
       \node (bg) [
         minimum width=\calPaperWidth + 6mm,
```

It does feel like the bottom trim is a bit tight as well, but I don't know how to fix *that* one.. ;)

Fairly minor issue, but I thought you should know. The image should have the proper (8.5x11) ratio, for what that's worth.

Thanks again!

**Comment by gambhiro** [comment]
Well done, good to hear your project went well.

The example in the class compiles with good alignment, perhaps the above error is caused by either whitespace getting into your title page setup (for example don't leave blanks between `\node` commands), or the pixel size of the image is not the same aspect as the page size.

Nonetheless, sometimes it is hard to track down, small position adjustments like what you did is exactly how I often deal with it as well.

I abstracted this kind of title page to a command, see if that works better.

```
% #1 : image path
% #3 : background overlay height
% #3 : title text
\TitlePage{DSCF2561.jpg}%
{60mm}%
{%
  \begin{minipage}{\calPaperWidth + 6mm}%
    \centering
    \josefinSans\fontsize{30}{50}\selectfont
    \CalendarYear\par
    Projet Calendes\par
  \end{minipage}%
}
```

**Comment by anarcat** [comment]
hmm... the `\TitlePage` extract you provided causes the same issue than i previously had. i ended up doing this:

```diff
-  \put(\LenToUnit{-3mm},\LenToUnit{-3mm}){%
+  \put(\LenToUnit{-4.5mm},\LenToUnit{-4.5mm}){%
     \begin{tikzpicture}
       \node (bg) [
-        minimum width=\calPaperWidth + 6mm,
-        minimum height=\calPaperHeight + 6mm,
+        minimum width=\calPaperWidth + 9mm,
+        minimum height=\calPaperHeight + 9mm,
       ] {%
-        \includegraphics[height={\calPaperHeight + 6mm}]{DSCF2561.jpg}%
+        \includegraphics[height={\calPaperHeight + 9mm}]{DSCF2561.jpg}%
       };
```

ie. move things around a little and make that specific image bigger so i have more room to maneuver. it's stange because I used the same process to produce that image than the other pages in the calendar, yet only that one is misaligned...

thanks for the help in any case! :)
