### ISSUE TITLE
Do you think you can add support for multiple events in one day?

### ISSUE THREAD

**Issue by T0071** [profound-labs/wallcalendar#18]
Multi-event in one day? like a list?

**Comment by gambhiro** [comment]
More description please, what kind of result are you trying to produce from what kind of input?

Try experimenting with the examples either in this repo, or the one [here](https://github.com/profound-labs/wallcalendar-portrait-layouts-overleaf).

Multiple events per day will work already, unless you found a particular bug.

Or perhaps you are asking about how to change their formatting?

**Comment by gambhiro** [comment]
Closing due to no updates. Comment if you are still stuck.
