### ISSUE TITLE
Name days at landscape calendar

### ISSUE THREAD

**Issue by flaiming** [profound-labs/wallcalendar#2]
Hi, first of all let me say that this is one really great written calendar. I have been just looking for exactly that. Just one thing - how hard would it be for me to make day numbers at landscape calendar page a bit smaller, aligned to corner and put into remaining space info whom name day is it? I'm a bit rusty on my latex skills, but I should manage if you could point me at right place in tex code where it should be done.
Thanks

**Comment by gambhiro** [comment]
You can define a new page layout and position everything as you wish.

The parts of the page (Photo, Calendar, Events) are placed in `xcoffins` boxes and these are positioned with an offset relative to the page.

Browse the code in `wallcalendar-code.pdf`, the Table of Contents will show how the macros are organized. See Section 10 (Page Layouts) to see where the layout macros are found.

Then I recommend opening `wallcalendar.cls`, copy one of the existing layout macros (such as `\@wall@smallLandscapeLayout`) and start making changes.

If you are thinking of a landscape calendar meaning that the calendar should lie on the long edge, add the desired paper size as a class option at the beginning (at [L74](https://github.com/profound-labs/wallcalendar/blob/master/wallcalendar.cls#L74) at the moment).

Perhaps it helps if you see that the end game of finishing a page is joining the particular coffins, see [L1071](https://github.com/profound-labs/wallcalendar/blob/master/wallcalendar.cls#L1071), and their contents are set before that.

**Comment by gambhiro** [comment]
Text sizes have formatting commands which can be redefined, but there is a reset before each layout macro, the redefining sizes have to go into a particular macro responsible for that such as `\smallLandscapeFmt` at [L922](https://github.com/profound-labs/wallcalendar/blob/master/wallcalendar.cls#L922).

The intention is that this macro (`\smallLandscapeFmt` in this case) can be then redefined in the preamble of your local calendar file.
