### ISSUE TITLE
Photo and Notes layout isn't working

### ISSUE THREAD

**Issue by cedvc** [profound-labs/wallcalendar#21]
When I try to use the Photo and Notes layout it isn't working.
The other lay-outs do work.

I even downloaded the example of github, but it didn't work.

I only get errors and the months are typed like normal text.
See picture: ![image](https://user-images.githubusercontent.com/74301001/98807753-6ad51b00-241b-11eb-83bb-ddd61eec82a0.png)

Is there a solution?

**Comment by cedvc** [comment]
What do I do wrong?
The Title-page also doesn't work

```
\documentclass[
    year=2021,
    language=english,
    imageFolder=./photos/,
    paperWidth = 11in - 15mm,
    paperHeight = 8.5in - 15mm,
    trimSpace = 15mm,
    topMargin = 15mm,
    showtrims,
    %showframe,
]{wallcalendar}

\makeatletter
\usepackage{fontspec}
\defaultfontfeatures{Ligatures={TeX}}
\setmainfont{TeX Gyre Pagella}
\newfontfamily\dejaVuSans{DejaVu Sans}

% =============== June ==============
\SetPhoto[bleed=3mm, file={soph-knok}]{June}


\SetEvents{June}{%
if (equals=2021-06-21)
[day text={\dejaVuSans\char"263C}];% U+263C white sun with rays
}{%
\raggedleft
{\dejaVuSans\char"263C} June 21: Summer Solstice}

\makeatother

\begin{document}

\TitlePage{ced}{60mm}{Test}
\MonthPage[layout=photo and notes, put photo=full page]{June}
\end{document}
```

**Comment by gambhiro** [comment]
Are you compiling the file in a separate folder? In that case it's probably using an old version of the package from TeXLive.

I tested your file, it works, try it like this:

- clone the wallcalendar repo
- add your calendar file in the repo root so it uses this version, not the one from TeXLive
- create the ./photos folder and add your pictures

Compile with lualatex

```
lualatex -interaction=nonstopmode -halt-on-error ./my-calendar.tex
```

**Comment by cedvc** [comment]
Thanks a lot!
It works, but how do I get the days of the week at the top of my calendar?
![image](https://user-images.githubusercontent.com/74301001/98826539-1ee39f80-2436-11eb-8dc2-449e52ba812e.png)


Thanks in advance

**Comment by cedvc** [comment]
Thanks a lot!
It won't load the csv files.
When I try to do it manually my text is on the bottom of the page

**Comment by gambhiro** [comment]
If you cloned the repo, I'd recommend opening the example file `doc/examples/cal-photo-and-notes.tex`, and edit it, removing the parts you don't need.

Its photo folder is `doc/examples/photos`, and edit the csv data in `doc/examples/data/holidays.csv`.

It is easier to remove parts from something that works, instead of building it up. It would be more elegant of course to separate out just your calendar files, but I hope this way you'll get your calendar PDF to the printer sooner.

**Comment by cedvc** [comment]
Thank you very much everything is working now!
