### ISSUE TITLE
Apply for Chinese Traditonal Calendar

### ISSUE THREAD

**Issue by xiaoleeza** [profound-labs/wallcalendar#3]
Your calendar is so awesome, I like it. But if there is a  Chinese Traditonal Calendar, it will be more perfect!
like this [https://www.chinasage.info/cal/calyear2018.htm](url)

**Comment by gambhiro** [comment]
Theoretically it should be possible, because it is basically just different unicode characters. Next week I will have more time to give it a try.

**Comment by gambhiro** [comment]
Looking at the link, it is not clear to me how the Chinese labels are used. For example I don't understand the meaning of `十五`, `十六`, `十七` for Jan 1, 2, 3.

https://www.chinasage.info/cal/calyear2018.htm

For an example of the translation, have a look at the [i18n/wallcalendar-japanese.tex](https://github.com/profound-labs/wallcalendar/blob/master/i18n/wallcalendar-japanese.tex) file.

The keys which can be translated are:

- month names (January, etc.)
- shortened month names (Jan, etc.)
- day names as letters (M, T, for Monday and Tuesday)

So I will need some help to move forward with this.

Although perhaps what you have in mind is the holidays, festivals and coloured days? To construct a calendar with these, you have to create a `.csv` file or add additional styling rules. See for example `doc/examples/cal-marks.pdf` and `doc/examples/cal-marks.tex` which read the holiday data from `doc/examples/data`.
