### ISSUE TITLE
Issues with notepad part in half/half layout

### ISSUE THREAD

**Issue by norbusan** [profound-labs/wallcalendar#6]
Hi,

thanks again, I am now creating calendars in various languages, and it works all very nicely. There is only one strange thing I cannot trace down:

With April 2019, I get only two lines of "......" at the bottom, despite there being only 5 lines in the calendar part.

My first guess was the fact that the "p" has a bigger descender, then other chars in the Pagella font, but adding a raisebox to set the descender to 0 didn't help either.

I attach April and May pages.

Thanks for any suggestion

![april-000001](https://user-images.githubusercontent.com/1735589/48389546-461d0e80-e741-11e8-942e-583dee031efb.png)
![may-000001](https://user-images.githubusercontent.com/1735589/48389549-49b09580-e741-11e8-8cbd-c15efa3d5f95.png)

**Comment by gambhiro** [comment]
Closing with PR #8. Thanks!
