### ISSUE TITLE
Wishlist: new layout that only does notes

### ISSUE THREAD

**Issue by norbusan** [profound-labs/wallcalendar#7]
I am using the "photo and notes" layout, but some of the photo pages I need to customize more by adding titles and arbitrary text.

It would be nice to have a 
```
  \MonthPage[layout=notes]{XXXX}
```
The only change to the photo and notes layout is that the
```
\clearpage
\TypesetCoffin\@wall@photoPageWrap%
```
needs to be removed, or made optional. For now I copied the definition of the original `\@wall@photoAndNotesLayout` and removed everything related to photo, but it might be better to refactor the rest of it into a common macro.

**Comment by gambhiro** [comment]
Do you mean adding formatted text under the calendar, instead of the dotted lines, or these are separate pages?

In the latter case you can simply put the content in the document body, between the `\MonthPage` commands, as with a regular LaTeX document.

**Comment by norbusan** [comment]
Yes, these are separate pages. My input files looks like:
```
% some TeX code for the page above the january calendar
\newpage
\MonthPage[layout=notes]{January}
% some TeX code for the page above the feb calendar
\newpage
\MonthPage[layout=notes]{February}
...
```

I attach the diff, but it duplicates most and is not really "intelligent" ;-)

[notes.txt](https://github.com/profound-labs/wallcalendar/files/2579743/notes.txt)

**Comment by gambhiro** [comment]
If they are separate pages, you can:

```
\MonthPage[layout=photo and notes, put photo=full page]{September}

\clearpage

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec hendrerit tempor
tellus. Donec pretium posuere tellus. Proin quam nisl, tincidunt et, mattis
eget, convallis nec, purus. Cum sociis natoque penatibus et magnis dis
parturient montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor.
Nullam tristique diam non turpis. Cras placerat accumsan nulla. Nullam rutrum.
Nam vestibulum accumsan nisl.

Aliquam erat volutpat. Nunc eleifend leo vitae magna. In id erat non orci
commodo lobortis. Proin neque massa, cursus ut, gravida ut, lobortis eget,
lacus. Sed diam. Praesent fermentum tempor tellus. Nullam tempus. Mauris ac
felis vel velit tristique imperdiet. Donec at pede. Etiam vel neque nec dui
dignissim bibendum. Vivamus id enim. Phasellus neque orci, porta a, aliquet
quis, semper a, massa. Phasellus purus. Pellentesque tristique imperdiet tortor.
Nam euismod tellus id erat.

\MonthPage[layout=photo and notes, put photo=full page]{October}
```

Does that work?

**Comment by norbusan** [comment]
But this generates an extra page with the Photo of September. 

My target is to *replace* the "photo" part with my own TeX code.

With the above code I get three pages for these months:

  - the photo page for the month
  - the calendar page
  - the page I added

Thanks

**Comment by gambhiro** [comment]
In other words, you want `\MonthPage` to produce only the calendar page, so that you can add custom pages in between (where the photo page would be)?

Which you could use as:

```
\clearpage

(... photo page code ...)

\MonthPage[layout=calendar notes]{September}

\clearpage

(... photo page code ...)

\MonthPage[layout=calendar notes]{October}
```

**Comment by norbusan** [comment]
Yes, that is exactly what I did achieve with the patch file I attached above (but only called it notes).

**Comment by gambhiro** [comment]
I'm sorry it took me a little while to understand what you were describing.

I added it as an option to `\SetPhoto` to avoid duplicating the layout code.

Now you can write:

```
\SetPhoto[disabled = true]{October}
```

The value of the key is stored and matched as a string.

With this you can implement the photo or other display-piece pages as regular content between the months.

```
\clearpage
(... nice things to look at in October ...)

\MonthPage[layout=photo and notes]{October}
```

Example and result:

https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/cal-no-photos.tex
https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/cal-no-photos.pdf
