### ISSUE TITLE
Wishlist: allow drawing of frame on the outside of days

### ISSUE THREAD

**Issue by norbusan** [profound-labs/wallcalendar#9]
It would be nice if optionally one can draw a line on the outside edges of the calendar, so that each day appears as one box.

**Comment by gambhiro** [comment]
I added it as a class option: `gridSurround`.

And I used the "no-photos" example to demonstrate:

https://github.com/profound-labs/wallcalendar/blob/master/doc/examples/cal-no-photos.pdf

**Comment by norbusan** [comment]
Thanks a lot!
